Added task 1 from dz 16
Igorwir/TMS_Leassons pull request #3
Opened 2022-04-26 10:34 UTC by Igorwir

Task 1 dz 16

2022-04-27 08:54 UTC, OKurcheuskaya requested changes

2022-04-27 08:54 UTC, OKurcheuskaya commented on app/src/main/java/com/example/tms_leassons/MainActivityDz16.kt
> +
не оставляй пустые строки

2022-04-27 08:54 UTC, OKurcheuskaya commented on app/src/main/res/layout/activity_main.xml
>          android:id="@+id/tx"
название id должно быть описательное

2022-04-27 08:54 UTC, OKurcheuskaya commented on app/src/main/res/layout/activity_main.xml
>          android:id="@+id/textViewInfo"
наименование id в формате tv_view_info, но лучше описательное

2022-04-27 08:54 UTC, OKurcheuskaya commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/pokaz"
наименование tv_pokaz

2022-04-27 14:56 UTC, Igorwir commented
В задании Added task 2 from dz 16 , находится 2 задачи.
В одной из них опять оставил пустые строки, постараюсь быть внимательнее в дальнейшем. Некоторые пустые строки делает сама AndroidStudia.

2022-04-28 05:40 UTC, OKurcheuskaya commented
> В задании Added task 2 from dz 16 , находится 2 задачи. В одной из них опять оставил пустые строки, постараюсь быть внимательнее в дальнейшем. Некоторые пустые строки делает сама AndroidStudia.

ничего) просто сделай новый коммит с  теми корректировками, которые я описала выше. Жду)

2022-04-29 11:00 UTC, OKurcheuskaya commented
наименование tv_pokaz
наименование id в формате tv_view_info, но лучше описательное
название id должно быть описательное

2022-04-29 11:00 UTC, OKurcheuskaya commented
не все изменения внес

2022-05-20 17:36 UTC, merged